#Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)

spring:
  profiles:
    active: ${ACTIVE_PROFILE:it}

  datasource:
    url: jdbc:h2:mem:twitterDemo
    username: it_db
    password:

