#Spring DATASOURCE (DataSourceAutoConfiguration & DataSourceProperties)

spring:
  profiles:
    active: ${ACTIVE_PROFILE:dev}

  datasource:
      url: jdbc:h2:mem:twitterDemo
      username: dev_db
      password:
  user:
      password: password
